apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-worker
  labels:
    app: auth-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-worker
  template:
    metadata:
      labels:
        app: auth-worker
    spec:
      containers:
        - name: cuppa-auth-worker
          image: cuppa/auth-worker
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: cuppa-auth-worker-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-auth-worker
  labels:
    app: auth
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30090
  selector:
    app: auth-worker
