// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package user

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           int64         `json:"id"`
	Name         string        `json:"name"`
	Email        string        `json:"email"`
	Password     string        `json:"password"`
	Enabled      bool          `json:"enabled"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	RefreshToken uuid.NullUUID `json:"refresh_token"`
}
