// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Source    string           `json:"source"`
	Token     pgtype.UUID      `json:"token"`
}

type User struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Enabled   bool             `json:"enabled"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Role      string           `json:"role"`
}
